// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZAuCbZYjJPOgbqWFAG3lJdsdCWT-OEM',
    appId: '1:52786343622:web:f3a7c0a5c1b22c5a35f1c7',
    messagingSenderId: '52786343622',
    projectId: 'whatsappclone704',
    authDomain: 'whatsappclone704.firebaseapp.com',
    storageBucket: 'whatsappclone704.appspot.com',
    measurementId: 'G-XWF9T9DYNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvm1XE6oZi-XYxWVmAGrnrDkwMrwLnBI',
    appId: '1:52786343622:android:eb36a07ff372a81835f1c7',
    messagingSenderId: '52786343622',
    projectId: 'whatsappclone704',
    storageBucket: 'whatsappclone704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-eGxCwA5LW2pBNeOjIg5QP9c4T1YQzps',
    appId: '1:52786343622:ios:312fb94ae21f8c9235f1c7',
    messagingSenderId: '52786343622',
    projectId: 'whatsappclone704',
    storageBucket: 'whatsappclone704.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-eGxCwA5LW2pBNeOjIg5QP9c4T1YQzps',
    appId: '1:52786343622:ios:13c9e0baff6206c035f1c7',
    messagingSenderId: '52786343622',
    projectId: 'whatsappclone704',
    storageBucket: 'whatsappclone704.appspot.com',
    iosBundleId: 'com.example.whatsappclone.RunnerTests',
  );
}
