// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_nMsPGs1dyUgCIq-NC3O2ykCwyIxQF_Y',
    appId: '1:482148508085:web:527ea039e6b7822e44b9fc',
    messagingSenderId: '482148508085',
    projectId: 'whatsapp704',
    authDomain: 'whatsapp704.firebaseapp.com',
    databaseURL: 'https://whatsapp704-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp704.appspot.com',
    measurementId: 'G-8WD50R5P93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1llVCIGUQgHO7G9aom5BNWNpI0rqNMFU',
    appId: '1:482148508085:android:658db6ee343139e144b9fc',
    messagingSenderId: '482148508085',
    projectId: 'whatsapp704',
    databaseURL: 'https://whatsapp704-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATN7AYbgm5geioyOa4OH4uPXMWPXrqIOI',
    appId: '1:482148508085:ios:b96e21bbede6d68b44b9fc',
    messagingSenderId: '482148508085',
    projectId: 'whatsapp704',
    databaseURL: 'https://whatsapp704-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp704.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATN7AYbgm5geioyOa4OH4uPXMWPXrqIOI',
    appId: '1:482148508085:ios:42c65a42d364d27a44b9fc',
    messagingSenderId: '482148508085',
    projectId: 'whatsapp704',
    databaseURL: 'https://whatsapp704-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp704.appspot.com',
    iosBundleId: 'com.example.whatsappclone.RunnerTests',
  );
}
